def call(body) {
    def config = [:]
    body.resolveStrategy = Closure.DELEGATE_FIRST
    body.delegate = config
    body()
    
    pipeline{
        agent any
        environment{
            BITBUCKET_PROJECT_URL = "https://github.com/pojjala/payments.git"
            REPOSITORY_ROOT = "payments"
            INCLUDE_PATTERN = "develope feature/app1"
            PROJECT_NAME = "ACIWorldWide"
            }
        stages{
            stage('Creation of folders'){
                    steps{
                        checkout scm
                        DSL Script :                          
                          def folderName = PROJECT_NAME.toUpperCase()
                          def adminGroup = "ROLE_${folderName}_ADMIN"
                          def opsGroup = "ROLE_${folderName}_READER"
                          folder(folderName) {
                              displayName(folderName)
                              description("Folder for project ${PROJECT_NAME} generated by ${JOB_NAME}")
                              authorization {
                                  permissions(opsGroup, [
                                      'hudson.model.Item.Read',
                                      'hudson.model.Item.ViewStatus',
                                      'hudson.model.View.Read'
                                   ])
                                    permissionAll(adminGroup) 
                                }
                                                   
                        }
                    }
                }
            }
      }
}
