

def folderName = "Prasad".toUpperCase()
def adminGroup = "ROLE_${folderName}_ADMIN"
def opsGroup = "ROLE_${folderName}_READER"
folder(folderName) {
    displayName(folderName)
  description("Folder for project ${PROJECT_NAME} generated by ${JOB_NAME}")
    authorization {
        permissions(opsGroup, [
            'hudson.model.Item.Read',
            'hudson.model.Item.ViewStatus',
            'hudson.model.View.Read'
        ])
        permissionAll(adminGroup) 
    }
}
